language: python
python:
  - "3.6"
cache: pip
install:
  - pip install .
  - pip install pytwoway
  - pip install codecov
script:
  - python -m pytest --cov-report term --cov=app/test/
after_success:
  - codecov