name: bpd-env
channels:
  - defaults
  - conda-forge
dependencies:
  # - python   # or 2.7 if you are feeling nostalgic
  - pip
  - pybind11
  - ipython
  - jupyterlab
  - notebook
  - pytest
  - numpy
  - numpy_groupies
  - pandas
  - tqdm
  - networkx
  - scipy
  - scikit-learn
  # - sphinx
  - nbsphinx
  - pip:
      - sphinx-rtd-theme # Sphinx theme
      - pytwoway
      # - pyarrow

# conda env create --file conda-env-file.yml
# conda env remove --name bpd-env
