name: bpd-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - pybind11
  - ipython
  - jupyterlab
  - notebook
  - pytest
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - statsmodels
  - igraph
  - tqdm
  - nbsphinx
  - pip:
      - sphinx-rtd-theme # Sphinx theme
      - pyarrow

# conda env create --file conda-env-file.yml
# conda env remove --name bpd-env
